management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  servlet:
    context-path: /shopee-naming-server
  port: 9000
spring:
   application:
      name: shopee-naming-server
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
         defaultZone: http://localhost:9000/shopee-naming-server/eureka
    